server:
  port: ${SERVER_PORT}
spring:
  application:
    name: tareamitocode
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVE}


oefa:
  url:
    front: ${URL_FRONT_OEFA_SIGSI}